### ISSUE TITLE
Mantendo o padrão

### ISSUE THREAD

**Issue by anteriovieira** [vuejs-br/br.vuejs.org#100]
Ao ler a documentação encontrei alguns termos escritos de formas diferente mas que passa a mesma ideia: Exemplo: **debaixo do capô** e **debaixo dos panos**, seria o caso de definir um padrão aqui? Eu estou revisando a documentação  e na medida que for encontrado outros eu vou reportando aqui.

**Comment by ErickPetru** [comment]
Colocação relevante a sua. Entendo que podemos ter um problema de regionalismo aí. Onde vivo no interior de São Paulo, **debaixo dos panos** é a única opção utilizada, mas padronizar desta forma poderia ser arbitrário. Existe alguma sentença não baseada em gírias com a mesma conotação?

**Comment by anteriovieira** [comment]
Então talvez usar algo mais técnico poderia evitar essa arbitrariedade: 

Sugestões:
- **em seu núcleo** ou **no seu núcleo**;
- **em seu interior** ou **no seu interior**

Exemplo:

"Os getter/setters são invisíveis para o usuário, mas **no seu núcleo** [ao invés de _debaixo do capô_], eles permitem ao Vue executar o rastreamento de dependência e notificações de alteração quando propriedades são acessadas ou modificadas."

@ErickPetru , também penso que tanto **debaixo do capô** quanto **debaixo dos panos** expressão a mesma ideia e talvez definirmos um como padrão também pode ser uma boa ideia.

**Comment by ErickPetru** [comment]
Particularmente gostei do **em seu interior**, podemos padronizar desta forma, tudo bem?

**Comment by anteriovieira** [comment]
Tudo bem, eu vou enviar um pull request com estas atualizações.

**Comment by ErickPetru** [comment]
Perfeitamente @anteriovieira. Já encerrei este _issue_ por já termos definido o padrão a ser adotado. Mas um _pull request_ com a revisão dos locais que carecem de alteração será muito bem-vinda.
