### ISSUE TITLE
Subitulos em MD devem ser tag HTML com id

### ISSUE THREAD

**Issue by Gutem** [vuejs-br/br.vuejs.org#108]
O pull request #31 traduz os subtitulos MD que são usados como ancora dentro do documento.
Se pegar o index.md da API, o item Vue.nextTick menciona `Async-Update-Queue` que é um subtitulo/parte dentro da documentação de reactivity.md, traduzido como `Fila de Atualização Assíncrona`, o que quebra as ligações externas de outros documentos.
O index.md da API usa `<h3 id"nome-do-subtitulo">`, que seria bom convencionar para uso em todo o documento para futuras traduções.

**Comment by ErickPetru** [comment]
Não sei se existe alguma forma melhor de lidarmos com isso, mas basicamente acontece com toda a documentação. Todos os subtítulos do guia foram traduzidos e, portanto, seus _links_ foram alterados em relação aos originais em inglês. Faz parte do trabalho de revisão garantir que todas as referências apontem para o local correto durante uma tradução. Eu particularmente faço um _replace all_ para todas as ocorrências de um _link_ que alterei quando estou traduzindo ou revisando algo. Alguma ideia diferente para tratarmos isso?

**Comment by Gutem** [comment]
Mencionei de usar `<h3 id"nome-do-subtitulo">` para tudo, como é feito no index.md da API... Acho que resolve o problema. 

Dei uma olhada em outros repos, em nenhum deles o pessoal se atentou a isso.

**Comment by ErickPetru** [comment]
Refletindo bastante sobre isso, não acho que devemos manter os _hashs_ em inglês. Da forma como está sendo feito, os _hashs_ acabam refletindo os títulos traduzidos, o que é muito mais semântico quando pensamos em URL amigáveis. Mas gostaria de ouvir opiniões de outros colaboradores antes de fechar o assunto.

**Comment by Halfeld** [comment]
Humm... Faz sentido colocar as hashs para português também, até pelas URL amigáveis.
Apesar que há casos que fica meio complicado traduzir algumas partes em inglês como algumas coisas que nos deparamos que só falamos em inglês xD

Enfim, minha conclusão geral é que faz sentido traduzir esses hashs para português, mas não vejo problemas em deixar algumas partes em inglês :D

**Comment by anteriovieira** [comment]
> Refletindo bastante sobre isso, não acho que devemos manter os hashs em inglês. Da forma como está sendo feito, os hashs acabam refletindo os títulos traduzidos, o que é muito mais semântico quando pensamos em URL amigáveis.

Concordo com a reflexão do @ErickPetru , e como @Halfeld mencionou, também não vejo problema em manter alguns termos em inglês. Já seguimos esse modelo na tradução - [Traduções-padronizadas](https://github.com/vuejs-br/br.vuejs.org#traduções-padronizadas).

**Comment by ErickPetru** [comment]
Vou fechar este tópico, com a conclusão de que **vamos manter a tradução dos títulos** quando apropriado, **inclusive nas URL**. Compete aos tradutores e revisores verificarem se todos os _links_ estão apontando para os endereços traduzidos.
