### ISSUE TITLE
Revomer parte em inglês deixada na tradução

### ISSUE THREAD

**Issue by marcelod** [vuejs-br/br.vuejs.org#111]
Estou iniciando com vue e vi na tradução um texto em inglês sendo que o mesmo já foi traduzido, em https://br.vuejs.org/v2/guide/join.html#Obtendo-Suporte

**Comment by ErickPetru** [comment]
Obrigado por avisar, atualizado no _commit_ https://github.com/vuejs-br/br.vuejs.org/commit/b0c887db59e76c451d168f5c7c980daa20122ee8.
