### ISSUE TITLE
Correção na página instalação

### ISSUE THREAD

**Issue by GeisonCamara** [vuejs-br/br.vuejs.org#114]
Na página de instalação (https://br.vuejs.org/v2/guide/installation.html) há um erro na seção **Vue Devtools**. 

Como está:
> Ao de mais nada, ao utilizar Vue também recomendamos que você instale a ...

Como deveria ser:
> Antes de mais nada, ao utilizar Vue também recomendamos que você instale a ...

**Comment by natanaelphp** [comment]
Vou mandar um Pull Request corrigindo. 
Obrigado por avisar.

**Comment by anteriovieira** [comment]
Boa pegada @GeisonCamara , pode nos enviar um pull request com as correções?

**Comment by natanaelphp** [comment]
Eu ia até mandar PR corrigindo, mas no código está certo.
O que ele está relatando é que na página esta diferente do código no repositório aqui.

**Comment by ErickPetru** [comment]
Exatamente @natanaelphp. Ocorre que o repositório está com diversos arquivos que precisam ser revisados por conflito de _merge_, visto que a documentação oficial recebeu muitas atualizações que conflitaram com as traduções anteriores. Não poderemos publicar novas versões do site antes de todos os conflitos serem resolvidos. _Pull requests_ são essenciais para atendermos esta demanda!

**Comment by ErickPetru** [comment]
Ocorreu um novo _deploy_ hoje com dezenas de correções e atualizações, incluindo o que foi reportado aqui.
