### ISSUE TITLE
(errinho) oficiente

### ISSUE THREAD

**Issue by and-dutra** [vuejs-br/br.vuejs.org#116]
Acredito que no paragrafo sobre substituir listas https://br.vuejs.org/v2/guide/list.html?#Substituindo-um-Array a palavra eficiente está escrita errada.

**Comment by ErickPetru** [comment]
Resolvido junto ao _commit_ https://github.com/vuejs-br/br.vuejs.org/commit/f2a466dcb4fdf23430b4d6ac66fce12047445e18.
