### ISSUE TITLE
"Transições de Estado" não foi traduzida

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#120]
A página referente a [Transições de Estado](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/transitioning-state.md) permanece em inglês e carece de tradução.

**Comment by davidson-bruno** [comment]
Trabalharei na tradução dessa página.

**Comment by davidson-bruno** [comment]
Se nenhuma alteração for feita, essa _issue_ poderia ser fechada.

**Comment by davidson-bruno** [comment]
@ErickPetru essa issue poderia ser fechada ou marcada como enhancement, caso tenha alterações para se fazer.
