### ISSUE TITLE
Diagrama em "Reatividade em Profundidade" poderia ser traduzido

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#121]
O diagrama existente no tópico [Como as Alterações são Monitoradas](https://br.vuejs.org/v2/guide/reactivity.html#Como-as-Alteracoes-sao-Monitoradas) poderia ser traduzido para melhorar a qualidade final do material.

**Comment by derevandal** [comment]
Eu não consegui abrir o .ai desse diagrama... Você conseguiu abrir aí?

**Comment by ErickPetru** [comment]
Não achei o `.ai` deste diagrama, provavelmente precisa ser criado do zero na versão original e enviado para o repositório principal, somente depois traduzido.
