### ISSUE TITLE
"Migração do Vue 1.x" não foi traduzida

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#122]
A página referente à [Migração do Vue 1.x](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/migration.md) permanece em inglês e carece de tradução.

**Comment by thiagofrancisquete** [comment]
Eu posso traduzir... tem algum prazo? To com pouco tempo agora, mas la pro dia 15 devo estar mais tranquilo

**Comment by ErickPetru** [comment]
Não temos prazo, afinal é um trabalho voluntário. Infelizmente, no passado, tivemos casos de colaboradores pegando determinado arquivo para traduzir e "sumindo" depois, o que é muito prejudicial para o andamento de todos. Por favor, confirme que está trabalhando neste arquivo para que eu possa marcar aqui com o _label_ `work-in-progress`.

**Comment by thiagofrancisquete** [comment]
Pode confirmar :smiley:

**Comment by rubenmarcus** [comment]
@ErickPetru  tem algum outro artigo para ser traduzido?

**Comment by rubenmarcus** [comment]
@ErickPetru  a parte de SSR não tem em português. Podemos começar ?
https://ssr.vuejs.org/en/api.html
Como?

**Comment by ErickPetru** [comment]
@rubenmarcus, a página alvo deste _issue_ continua sem tradução, infelizmente. Não vejo problemas se fizer esta tradução.

**Comment by danielschmitz** [comment]
@ErickPetru Ainda está sem tradução? Quer q eu pegue pra fazer?

**Comment by thiagofrancisquete** [comment]
@ErickPetru ja esta traduzida, mas faltam 2/3 do _markdown_ pra passar, aumentou meu volume no serviço e não terminei de editar ainda... o aumento de volume/carga não estava programado, por isso a demora

**Comment by danielschmitz** [comment]
Mas voce comitou? Se sim, beleza
Ah, vc pode adicionar no comentário do seu commit o numero da issue assim #122 Com isso o commit fica registrado na thread da issue e podemos saber que ela n está parada ;)

**Comment by ErickPetru** [comment]
@thiagofrancisquete, acrescentando ao que o @danielschmitz colocou, imprevistos de trabalho acontecem e não tem problema nenhum, também passo por isso. Só recomendo não deixar o arquivo muito tempo parado na mão se as coisas complicaram. Às vezes é melhor enviar o _pull request_ com o trabalho parcial e usar a _issue_ para descrever o que ficou faltando, assim outros podem se propor a continuar.

**Comment by thiagofrancisquete** [comment]
@ErickPetru o pull vai pro vue ou pro vue-br?

**Comment by danielschmitz** [comment]
pull é para o vue-br

**Comment by hhalmeida** [comment]
Fala galera, quero apoiar o projeto, onde vejo o que precisa ser traduzido? 
abraços...

**Comment by GuiDevloper** [comment]
Meu sonho é ter coragem o suficiente para traduzir essa página.
Pense em uma história boa pra contar, é o que terá quem trabalhar nessa tradução.

**Comment by GuiDevloper** [comment]
@ErickPetru Eu acho que entendi o que está gerando o erro, uma falta de código necessário ser mantido.
Eu não trabalhei naquele por esperar o autor da _PR_, entende?
Como eu posso ajudar a conserta-la?

**Comment by ErickPetru** [comment]
Faz bastante tempo que o PR está parado, não acho que o autor pretenda resolver o conflito. Se você puder enviar outro commit no PR resolvendo o conflito, poderemos finalmente fazer o merge.

**Comment by GuiDevloper** [comment]
@ErickPetru Desculpa o meu jeito novato, mas mesmo tendo pensado nisso, acho que não posso pois _add commits_ não é só para quem tem _write access_ à _PR_?

**Comment by ErickPetru** [comment]
Teoricamente, é possível enviar novos commits a um PR de um fork, desde que você tenha permissão para enviar PRs diretamente para a origem do fork. Mas se não for possível, sem problemas. Como se trata de um único arquivo, pegue a versão mais recente e faça um diff com a que foi enviada, aproveitando tudo que for possível da tradução feita e complementando com algo que seja necessário. Depois envie seu próprio PR.
