### ISSUE TITLE
Diagrama em "Componentes" poderia ser traduzido

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#123]
O diagrama existente no tópico [Compondo Componentes](https://br.vuejs.org/v2/guide/components.html#Compondo-Componentes) poderia ser traduzido para melhorar a qualidade final do material.

**Comment by MatheusRich** [comment]
Há algum tipo de padronização para tradução de imagens como essa?

**Comment by ErickPetru** [comment]
Não chega a ser efetivamente uma padronização, mas temos um exemplo prático em [Diagrama de Ciclo de Vida](https://br.vuejs.org/v2/guide/instance.html#Diagrama-do-Ciclo-de-Vida). Observe que é realmente uma tradução bem direta dos termos e frases que eram convenientes feita exatamente no mesmo modelo do diagrama em inglês.

**Comment by MatheusRich** [comment]
@ErickPetru Eu gostaria de trabalhar nisso. Você sabe qual a fonte utilizada?

**Comment by ErickPetru** [comment]
Dentro da pasta `assets` há arquivos com extensão `.ai` para os diagramas de ciclo de vida e de gerenciamento de estado. Este diagrama de componentes parece que esqueceram de salvar o arquivo original, mas deve ser simples montar um igual e usar a mesma fonte usada nos arquivos que citei.

**Comment by MatheusRich** [comment]
Vou reproduzir o diagrama num arquivo `.ai`. Seria interessante adicioná-lo à pasta `assets` em seguida? 

Posso ficar com essa issue? A label `work-in-progress` deve ser adicionada por mim ou por você?

**Comment by ErickPetru** [comment]
Acho que só eu consigo alterar os _labels_, na dúvida já fiz agora. Quanto a gerar o arquivo `.ai` inexistente e colocar na pasta `assets`, ótimo!

Sugestão adicional: gere ele em inglês também e faça um _pull request_ para o repositório principal, assim outras equipes de tradução de outros idiomas podem aproveitá-lo.

**Comment by MatheusRich** [comment]
Refiz o diagrama o mais próximo possível do original (imagem abaixo). Eu devo fazer o pull request neste fork primeiro, ou no oficial?

**Em inglês**
![state](https://user-images.githubusercontent.com/20938712/33663685-1dcf135a-da78-11e7-9acb-df799baa090d.png)

**Em português**
![state - br](https://user-images.githubusercontent.com/20938712/33663666-0482effc-da78-11e7-9a71-9963c78925f0.png)

**Comment by ErickPetru** [comment]
Ficou ótimo! Faça _pull request_ aqui para o traduzido e pode fazer diretamente lá para o outro, destacando que a pasta `assets` não tinha esse material e que tomou a iniciativa de produzi-lo durante a tradução para pt-BR.

**Comment by MatheusRich** [comment]
Enviei o PR (#126)

**Comment by ErickPetru** [comment]
Já foi aceito. Você vai atualizar também o arquivo exportado e o caminho no guia?

**Comment by MatheusRich** [comment]
Posso fazer isso também. Em breve envio.
