### ISSUE TITLE
Diagrama em "Gerenciamento de Estado" poderia ser traduzido

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#124]
O diagrama existente no tópico [Gerenciamento de Estado do Zero](https://br.vuejs.org/v2/guide/state-management.html#Gerenciamento-de-Estado-do-Zero) poderia ser traduzido para melhorar a qualidade final do material.

**Comment by derevandal** [comment]
@ErickPetru tu sabe a fonte que é usada?
