### ISSUE TITLE
"API" não foi revisada

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#125]
A enorme página referente a todo o conteúdo da [API](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/api/index.md) não passou por uma revisão completa da tradução, não estando totalmente padronizada em relação às outras. Destaca-se o problema de alguns _links_ apontando para os locais errados do Guia.

**Comment by derevandal** [comment]
Irei revisar a API. @ErickPetru

**Comment by derevandal** [comment]
@ErickPetru dá uma olhada no PL.

**Comment by ErickPetru** [comment]
Ótimo trabalho, me parece que vários problemas foram resolvidos.
