### ISSUE TITLE
Erro de concordância verbal em "Publicando em Produção"

### ISSUE THREAD

**Issue by davidson-bruno** [vuejs-br/br.vuejs.org#127]
No trecho "Entretanto, _estas Strings_ de aviso se **torna** desnecessárias (...)" o verbo não concorda com o número do substantivo em questão. Uma sugestão de tradução melhor seria "Entretanto, _essas Strings_ de aviso se **tornam** desnecessárias (...)".

**Comment by davidson-bruno** [comment]
Se nenhuma alteração for feita, essa _issue_ poderia ser fechada.

**Comment by derevandal** [comment]
@ErickPetru fecha a issue que já foi feito merge ;)
