### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by MarlonJhow** [vuejs-br/br.vuejs.org#135]
Em Introdução >> Composição com Componentes (https://br.vuejs.org/v2/guide/index.html#Composicao-com-Componentes) 

O seguinte trecho esta com a palavra **podemos** com erro de digitação:
Este é um exemplo fictício, mas conseguimos separar nossa aplicação em duas pequenas unidades, sendo que o componente filho está razoavelmente bem desacoplado do componente pai graças à funcionalidade de props. **Ppodemos** agora melhorar nosso componente <todo-item> com template e lógica mais complexos, sem afetar o restante.

**Comment by ErickPetru** [comment]
Duplicate of https://github.com/vuejs-br/br.vuejs.org/issues/131
