### ISSUE TITLE
Tradução da documentação do vue-router

### ISSUE THREAD

**Issue by leandroruel** [vuejs-br/br.vuejs.org#136]
Olá, gostaria de ajudar a traduzir a página do vue-router, como posso fazê-lo?

**Comment by derevandal** [comment]
@leandroruel tu tem que fazer lá na repositório do vue router:
https://github.com/vuejs/vue-router

**Comment by ErickPetru** [comment]
@leandroruel, você pode fazer um _fork_ do repositório do **vue-router**, criar uma pasta **pt-br** e traduzir. Depois envia o _pull request_ e aguarda a revisão. Se quiser um exemplo de como fica, fizemos isso com o repositório do **vue-test-utils**: https://github.com/vuejs/vue-router/tree/dev/docs

**Comment by leandroruel** [comment]
mas eu do pull la no repositorio do vue-router ne? tentei criar uma issue la pra pedir pra traduzir mas tem um bot que fecha automaticamente a issue assim que é criada.

**Comment by ErickPetru** [comment]
Isso, os repositórios dos projetos paralelos mantém todas as traduções, diferente do site oficial que é separado. O processo ocorre todo por lá. Quando a _issue_, não se preocupe, já está registrado por aqui que você vai trabalhar nisso, a chance de algum outro brasileiro pegar pra traduzir direto por lá sem passar por aqui é mínima.

**Comment by leandroruel** [comment]
Ok meu caro, obrigado, vou fazer isso hoje a noite. pretendo ir traduzindo de pouquinho em pouquinho conforme a disponibilidade

**Comment by anteriovieira** [comment]
@ErickPetru  acho que seria o caso de fazermos um fork de **vuejs/vue-router** para **vuejs-br** e centralizar todas as contribuições aqui. Dai o pessoal pode revisar antes de enviar para o repositório principal. O que você acha?

**Comment by leandroruel** [comment]
pra mim é melhor!

**Comment by ErickPetru** [comment]
Se preferem desta forma, por mim tudo bem. _Fork_ realizado: https://github.com/vuejs-br/vue-router

**Comment by anteriovieira** [comment]
Perfeito, 

@leandroruel , agora só você fazer o fork do repositório https://github.com/vuejs-br/vue-router e enviar os pull requests com as traduções. Qualquer dúvida só abrir uma issue em **vuejs-br/vue-router**.

Estou fechando está issue por entender que foi resolvido.

**Comment by leandroruel** [comment]
galera so lembrando aqui que estou traduzindo aos poucos, nao abandonei

**Comment by anteriovieira** [comment]
tranquilo @leandroruel
