### ISSUE TITLE
Tradução do Nuxt.js

### ISSUE THREAD

**Issue by derevandal** [vuejs-br/br.vuejs.org#140]
@ErickPetru você poderia colocar dentro da org vuejs-br um fork da [documentação do nuxt.js](https://github.com/nuxt/docs) para podermos trabalhar na tradução também? 
Ultimamente eu tenho usado muito o Nuxt e, com a chegada da v1.0, acredito que uma versão em pt-br vai ajudar a comunidade...
Além disso, centralizar tudo na vuejs-br facilitaria muito a gestão, não acha?

Espero que consiga fazer isso e obrigado pela atenção!

**Comment by ErickPetru** [comment]
Acho ótimo traduzir a documentação do Nuxt, também uso e gosto muito dele. Porém, li na postagem de lançamento do 1.0 que eles estão trabalhando em muitas mudanças na documentação nas próximas semanas, então não sei se o retrabalho não seria exagerado neste momento.

De qualquer forma, já criei o _fork_ solicitado e recomendo que tentem se integrar com a equipe oficial para entender as mudanças planejadas e evitar o excesso retrabalho.
