### ISSUE TITLE
Tradução da documentação do vuejs-templates/webpack

### ISSUE THREAD

**Issue by cristianl** [vuejs-br/br.vuejs.org#145]
Estava lendo os [docs do template Webpack](https://github.com/vuejs-templates/webpack/tree/develop/docs) usado pelo vue-cli, e notei que ainda não há nenhuma tradução no projeto.

Posso traduzi-la e acompanhar as mudanças no original para mantê-la atualizada. Há interesse em colocá-la sob a organização vuejs-br?

**Comment by ErickPetru** [comment]
Legal @cristianl, particularmente acredito que quanto mais documentações tivermos tradução, mais visibilidade traremos ao Vue no Brasil. Fiz _fork_ do repositório do modelo [Webpack](https://github.com/vuejs-br/template-webpack) e também do modelo [PWA](https://github.com/vuejs-br/template-pwa), os dois mais "estrelados" entre os _templates_.

Aproveitando a oportunidade, gostei muito da qualidade de suas revisões no guia. Acabo de adicioná-lo ao time de contribuidores da organização, para facilitar seu trabalho em todos os repositórios.

**Comment by cristianl** [comment]
Obrigado @ErickPetru! Acompanho o Vue há tempo mas só pude usá-lo recentemente. A comunidade Vue brasileira me fascina e me inspira a aprender e colaborar.

Esta tradução está tão completa (só faltando a página de migração do 1.0) e fluente que até achei pedante fazer pequenas alterações, mas torço para o material ajudar mais gente a conhecer e criar com Vue.

Quando puder, darei uma olhada nos demais repositórios.
