### ISSUE TITLE
Erro de gramática na tradução.

### ISSUE THREAD

**Issue by dionisioviei** [vuejs-br/br.vuejs.org#146]
Onde foi escrito "Vue (_pronuncia-se /vjuː/,_ como view, em inglês)" logo no inicio, possui um erro logo após **'pronuncia-se** onde no lugar do j seria um i: **'pronuncia-se /viu'**

**Comment by ErickPetru** [comment]
Isto não é um erro de gramática, é a representação da pronúncia em inglês utilizando o Alfabeto Fonético Internacional, onde **/j/** tem o som equivalente ao nosso **i**. Observe que a [versão em inglês do guia](https://vuejs.org/v2/guide/) apresenta a mesma grafia, pois o alfabeto fonético é internacional. Segue tabela para referência:

![image](https://user-images.githubusercontent.com/242274/35626520-1a35639e-067d-11e8-9892-5a576e378ea8.png)
