### ISSUE TITLE
os artigos já foram todos traduzidos? 

### ISSUE THREAD

**Issue by rubenmarcus** [vuejs-br/br.vuejs.org#147]
Tinha uma lista aqui de artigos a serem traduzidos, e eu estava nela, e não tinha cumprido o combinado, e queria traduzir o artigo agora, como faço? Já foi feito? Pode revisar algum ?

**Comment by ErickPetru** [comment]
Quase todos os itens abertos já foram fechados por terem sido resolvidos. Entretanto, atualizações vão sendo lançadas ao guia oficial e novas itens acabam sendo abertos. O "Guia de Estilo" é um bom exemplo disso.

**Comment by danielschmitz** [comment]
Olá @rubenmarcus 
Se quiser pode terminar o #122, que é o guia de migração. Ele começou a ser traduzido mas parou no meio, acredito eu.
