### ISSUE TITLE
"Guia de Estilo" não foi traduzido

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#148]
Embora ainda esteja marcado como **beta**, a equipe responsável garantiu que poucas mudanças são esperadas para o futuro próximo, portanto a tradução de toda esta nova área da documentação já é possível.

**Comment by hhalmeida** [comment]
Fala galera, quero apoiar o projeto, onde vejo o que precisa ser traduzido?
abraços...

**Comment by ErickPetru** [comment]
O que a equipe já identificou fica registrado aqui como _issue_ e o pessoal vai falando o progresso para deixar tudo mais organizado. Esta _issue_ é um bom exemplo do processo.

Eventualmente alguns problemas de tradução ou trechos não traduzidos podem ser encontrados se aprofundando na documentação, aí quem achou pode criar _issue_ aqui para registrar o problema e atuar para resolver, se puder.

**Comment by hhalmeida** [comment]
Legal @ErickPetru , muito obrigado, ao achar algo eu abro a issue e já faço o PR.

**Comment by danielschmitz** [comment]
Lembrando que essa issue esta no seu respectivo branch issue-148 

@erickpetru nesse carnaval nao vou trabalhar nesta issue. Volto a traduzir após o carnaval.
