### ISSUE TITLE
Atualizar tradução de "Funções de Renderização"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#150]
Um novo tópico foi acrescido na documentação em inglês, [Passing Attributes and Events to Child Elements/Components](https://br.vuejs.org/v2/guide/render-function.html#Passing-Attributes-and-Events-to-Child-Elements-Components), precisando de tradução para o português.

**Comment by kimuraz** [comment]
@ErickPetru posso ficar com essa issue?

**Comment by ErickPetru** [comment]
Ótimo @kimuraz, vai fundo.
