### ISSUE TITLE
Erro de sintaxe na tradução da página: https://br.vuejs.org/support-vuejs/

### ISSUE THREAD

**Issue by MarioDeAraujoCarvalho** [vuejs-br/br.vuejs.org#153]
A palavra '**projeto**' está com sintaxe errada:

**Texto original**: Vue.js é um projeto _open source_ sob licença MIT e completamente gratuito para usar. Entretanto, a quantidade de esforço necessário para manter e desenvolver novos recursos para o **prpjeto** não é sustentável...
Texto corrigido: 

**Texto corrigido**: Vue.js é um projeto _open source_ sob licença MIT e completamente gratuito para usar. Entretanto, a quantidade de esforço necessário para manter e desenvolver novos recursos para o **projeto** não é sustentável...

Sou novo no Vue, e estou estudando toda a documentação, e gostaria de aproveitar essa oportunidade para ajudar a traduzir o projeto ou mesmo contribuir com exemplos, respondendo dúvidas etc. 

Abraços.

**Comment by ErickPetru** [comment]
Resolvido em https://github.com/vuejs-br/br.vuejs.org/commit/b9a85503add2538143d5d870189977e107bb1767.

**Comment by MarioDeAraujoCarvalho** [comment]
Maravilha!

Abraços.
