### ISSUE TITLE
Form Select o código está incompleto.

### ISSUE THREAD

**Issue by romenigld** [vuejs-br/br.vuejs.org#156]
And I saw something incomplete in this link:
Olá pessoal estou lendo o Vuejs.org e eu vi que está incompleto o código.
[vuejs-forms-guide-select](https://br.vuejs.org/v2/guide/forms.html#Select)
```
new Vue({
el: ‘…’,
data: {
selected: ‘’
}
})


```
De acordo com o que esotu aprendendo acho que deve ser assim:
```
var example = new Vue({
el: ‘#example’,
data: {
selected: this.selected
}
```

**Comment by romenigld** [comment]
I do a pull request for this now.

**Comment by ErickPetru** [comment]
Este repositório apenas realiza a tradução da documentação oficial, caso realmente acredite que algo deve ser modificado no código de exemplo, a _issue_ deve ser aberta em https://github.com/vuejs/vuejs.org. Mas aproveito a oportunidade para informar que não há erro no código citado, tanto é que ele funciona ao vivo ali mesmo na página da documentação que foi referenciada.

**Comment by romenigld** [comment]
desculpa ai @ErickPetru como eu vi esses 3 pontos(...) pensei que faltava algo. vlw e desculpa ae..
