### ISSUE TITLE
Correção tradução - vue-test-utils

### ISSUE THREAD

**Issue by hhalmeida** [vuejs-br/br.vuejs.org#158]
Fala pessoal, Tudo bem?

To usando a documentação da parte de teste do Vue e achei alguns erros, gostaria de apoiar, eu poderia fazer as correções e fazer um PR?, como devo proceder para apoiar a comunidade?

Antecipando, caso eu não possa apoiar, vou pontuar os erros para correção.

**Instalação do vue-test-utils**
_De:_
`$ npm install --save-dev jest vue-test-utils`
_Para:_
`$ npm install --save-dev jest @vue/test-utils` || `$ npm i -D jest vue-test-utils`
_ou fazer as instalações separadas ::_ 
`$ npm i -D jest`
`$ npm i -D vue-test-utils`

**Exemplo de spec**
_Foi traduzido parte do código:: 
De:_ 
```
describe('Componente', () => {
  test('é uma instância do Vue', () => {
    const wrapper = mount(Componente)
    expect(wrapper.ehInstanciaVue()).toBeTruthy()
  })
})
```

_Para:_
```
describe('Componente', () => {
  test('é uma instância do Vue', () => {
    const wrapper = mount(Componente)
    expect(wrapper.ehInstanciaVue()).toBeTruthy()
  })
})
```

Bom valeu pela tradução galera... tem sido muito util.

**Comment by ErickPetru** [comment]
Olá @hhalmeida, não temos um repositório aqui para a tradução do **vue-test-utils**, pois não foi feita por aqui, foi conduzida diretamente no repositório original. Recomendo que faça um pull request em inglês lá descrevendo as alterações no arquivos necessários da pasta https://github.com/vuejs/vue-test-utils/tree/dev/docs/pt-br.
