### ISSUE TITLE
Problemas nas imagens

### ISSUE THREAD

**Issue by TiagoHA** [vuejs-br/br.vuejs.org#160]
Problemas nas imagens

https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/single-file-components.md

**Comment by ErickPetru** [comment]
As imagens estão funcionando normalmente no _site_ em execução: https://br.vuejs.org/v2/guide/single-file-components.html. É natural que não funcionem diretamente no GitHub por questões de caminho de arquivo.
