### ISSUE TITLE
tradução

### ISSUE THREAD

**Issue by TihFerA** [vuejs-br/br.vuejs.org#161]
=> https://br.vuejs.org/v2/guide/list.html

"Note the is="todo-item" attribute. This is necessary in DOM templates, because only an < li > element is valid inside a < ul >. It does the same thing as <todo-item>, but works around a potential browser parsing error. See DOM Template Parsing Caveats to learn more."

=> https://br.vuejs.org/v2/guide/events.html
"Teclas modificadoras são diferentes de teclas comuns, e quando utilizadas com eventos keyup, precisam estar pressionadas quando o evento é emitido. ...."

a tradução não está com a formatação correta e logo abaixo ainda aparece o texto original em inglês.

**Comment by Murillofilho86** [comment]
Não ficou muito claro... 
O problema é a div (<div @click.ctrl="doSomething">**Do something**</div>)? Ou Este problema já foi corrigido?
