### ISSUE TITLE
Tradução do "cookbook/unit-testing-vue-components.md"

### ISSUE THREAD

**Issue by danielschmitz** [vuejs-br/br.vuejs.org#164]

**Comment by ericdouglas** [comment]
Gostaria de ajudar traduzindo esse arquivo.

**Comment by ErickPetru** [comment]
Olá @GuiDevloper, ninguém está trabalhando nele não. Se confirmar sua participação, colocamos em andamento no board do Cookbook: https://github.com/vuejs-br/br.vuejs.org/projects/3

**Comment by GuiDevloper** [comment]
Então pode confirmar, estou dentro @ErickPetru
