### ISSUE TITLE
Tradução do "cookbook/editable-svg-icons.md"

### ISSUE THREAD

**Issue by danielschmitz** [vuejs-br/br.vuejs.org#165]

**Comment by HmmerHead** [comment]
Posso contribuir?

**Comment by ErickPetru** [comment]
Certamente, @HmmerHead! Siga as instruções do README e depois envie um _pull request_ de seu _fork_ com a tradução realizada.

**Comment by HmmerHead** [comment]
Mandei um pull request. Não sei se está todo certo. Estou a disposição para qlqer coisa

**Comment by ErickPetru** [comment]
Obrigado pela colaboração @HmmerHead. Já fiz a revisei e publiquei o _pull request_ #204. Depois, se quiser, dê uma olhada em como ficou após revisado para identificar alguns pontos que precisaram de correção.
