### ISSUE TITLE
Git conflito em produção.

### ISSUE THREAD

**Issue by anologicon** [vuejs-br/br.vuejs.org#185]
Pessoal, a página da doc https://br.vuejs.org/v2/guide/components.html#Propriedades, esta com conflito do git.

**Comment by odahcam** [comment]
![image](https://user-images.githubusercontent.com/3942006/44918377-2153f600-ad11-11e8-99d3-8cd86efb70c5.png)

**Comment by anologicon** [comment]
Foi nesse PR. https://github.com/vuejs-br/br.vuejs.org/commit/9d6d1e60ba92db9b4b4dd7f761b7661da62f1a45#r30358040

**Comment by angeliski** [comment]
A página de componentes também:
https://br.vuejs.org/v2/guide/components.html#Opcao-data-Deve-Ser-uma-Funcao
