### ISSUE TITLE
Tradução do "cookbook/avoiding-memory-leaks.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#192]

**Comment by GuiDevloper** [comment]
Hey @ErickPetru estou pensando em traduzir este, ele contém links para CodePen.
E necessário traduzi-los? Se sim, posso forkar os exemplos e linkar do meu Pen traduzido?

**Comment by ErickPetru** [comment]
Até agora não fizemos isso, mas acho que fica bem melhor fazer. Até marquei esta melhoria em outro documento. Então se já puder seguir assim, melhor ainda.
