### ISSUE TITLE
Tradução do "cookbook/packaging-sfc-for-npm.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#197]

**Comment by IgorVieira** [comment]
Posso pegar essa parte também?

**Comment by raphamendonca** [comment]
work-in-progress

**Comment by raphamendonca** [comment]
Acabo de efetuar o PR #197 tradução do aruivo cookbook/packaging-sfc-for-npm.md
 para a tradução desse arquivo.
