### ISSUE TITLE
Tradução do "guide/components-slots.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#202]

**Comment by el-cardu** [comment]
Boa noite, tudo bom?!

Verifiquei o backlog, vi essa pendência e estou pensando em começar a ajudar na tradução por aqui, posso começar? Se sim, pode confirmar que estou dentro! :tada:

**Comment by ErickPetru** [comment]
Isso aí @el-cardu, o arquivo está pendente sim, pode mandar ver.

**Comment by IFormiga** [comment]
Vou trabalhar na tradução hoje!

**Comment by raphamendonca** [comment]
Vou efetuar a tradução dessa pagina.

**Comment by henriquehbr** [comment]
Efetuei a tradução completa da página `components-slots.md` nesse [commit](https://github.com/henriquehbr/br.vuejs.org/commit/45690799dfbe3ed1b311d357c534ce8f806eeae9)
