### ISSUE TITLE
Revisão completa do "style-guide/index.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#226]
O Guia de Estilos é apresentado em um único arquivo, com muito conteúdo. Desta forma, a tradução inicial acabou sendo feita de forma apressada em alguns pontos. Há frases traduzidas de forma equivocada, inclusive algumas que perderam o significado original. Diversos padrões do restante da documentação também não foram seguidos. Uma revisão completa se faz necessária.

**Comment by GuiDevloper** [comment]
Hey Erick, tudo bem?
Como está essa revisão? Ela é importante pois fecha a #243 também.
Precisando, eu posso ajudar.

**Comment by ErickPetru** [comment]
Olá @GuiDevloper, tudo bem? Na verdade, não consegui concluir uma revisão tão abrangente quanto gostaria, mas diria que uns 65% foram revisados. Estou terminando de escrever meu segundo livro, então o tempo está curto. De qualquer forma, subi o arquivo **style-guide/index.md** caso alguém queira se aprofundar na revisão a partir de onde parei.

Independentemente disso, não entendi qual a relação o guia de estilo tem com a _issue_ #243 relacionada a páginas do guia principal. Entendi errado alguma coisa?

**Comment by GuiDevloper** [comment]
Estou bem, procurando sempre ajudar.
Boa inspiração com o novo livro!
A #243 está relacionada com 'capítulos' do [style-guide](https://br.vuejs.org/v2/style-guide) que é o arquivo [style-guide/index.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/style-guide/index.md), se eu estiver equivocado pode dizer.

PS: inclusive seu novo update já fecha aquela issue :)
