### ISSUE TITLE
VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [vuejs-br/br.vuejs.org#242]
Hello! 

My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Português-Br translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

**Comment by ErickPetru** [comment]
Hi @bencodezen, very nice news to hear. I think there are just some questions:
- Is there already a repo or branch we can take a look to see how the things are going one?
- Will the `.md` files stay the same until the initial release? Or will we need to copy and past translations between files to handle a different structure?
- Currently, our translation is a direct fork of the official repo. Can our workflow be maintained this way? Or it will become only the main repo with folders for translations, as we already see in vue-router or vuex docs?
- Our fork has CI on Netlify, whose subdomain [br.vuejs.org](br.vuejs.org) has been configured there by Evan. Will we keep it this way? Or the direct deploy of our translation to the subdomain will not be needed anymore?

**Comment by bencodezen** [comment]
Hi @ErickPetru!

1. We are currently in the planning phases so no official roadmap or repo yet. We wanted to give translators a chance to give feedback before embarking on this journey.
2. I think that they should be the same for the most part. If there are any significant changes as far as migration effort, we will make sure to document it for everyone.
3. As of right now, we plan on leaving the workflow alone for the all of the different translators. There is some discussion about whether there could be a more formalized process for everyone, but we will definitely reach out if we want to suggest any changes.
4. Yes this should be the same for now as far as I'm aware. If anything is going to change, we will be sure to reach out.

**Comment by bencodezen** [comment]
If anyone has any additional feedback, please don't hesitate to re-open the issue and/or tag me in a new one!
