### ISSUE TITLE
How update works?

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/br.vuejs.org#247]
Estive dando uma visão geral na Doc e encontrei bugs como o link de demo do [exemplo HackerNews](https://br.vuejs.org/v2/examples/hackernews.html) que porém já foi resolvido na [original](https://github.com/vuejs/vuejs.org/commits/master/src/v2/examples/hackernews.md).
Como funciona a sincronização com o original?
Reiniciaria as traduções ou tem alguma mediação antes do _pull_?

**Comment by ErickPetru** [comment]
Basicamente, é um `fetch upstream` seguido de um `pull upstream master`. O problema é que normalmente isso resulta em vários conflitos a resolver antes do `merge`, para evitar colocar no ar qualquer conflito não resolvido, já que qualquer coisa em _master_ é automaticamente refletida no Netlify. Até hoje, eu sempre fiz isso e resolvi os conflitos, mas a limitação é que depende da minha disponibilidade, o que é bem chato.

Penso que uma alternativa seria criar um _branch dev_ em nosso repositório e fazer `pull upstream dev`, resolver tudo ali e depois enviar para _master_ quando já estivesse revisado. Assim outras pessoas poderiam ajudar a resolver os conflitos em _dev_. O que acha desse processo?

**Comment by GuiDevloper** [comment]
Bem interessante essa ideia, dividiria entre a comunidade a responsabilidade por manter atualizado.
Só o BR mesmo que vi com ideia assim.
Outra coisa legal seria colocar esse `dev` no [projects](https://github.com/vuejs-br/br.vuejs.org/projects) explicitando as maiores divergências a serem resolvidas.
Você vê problemas na criação desse _branch_?
Sei que deverei atualizar meu _fork_, mas algo mais?

**Comment by ErickPetru** [comment]
Olá novamente @GuiDevloper, boas notícias! O novo _branch_ `dev` está pronto com as últimas versões sincronizadas com o repositório principal. O mais legal é que o Netlify permite o deploy automático também deste _branch_, sendo possível observar todos os _deploys_ realizados e acessar suas versões publicadas em: https://app.netlify.com/sites/br-vuejs-org/deploys.

Dito isto, há diversos conflitos de _merge_ a serem resolvidos. Imagino que o próximo passo é termos _pull requests_ para os conflitos resolvidos nesse _branch_. Quando todos estiverem resolvidos, eu faço o _merge_ em _master_ e ficará tudo atualizado. Me parece um processo consistente. E o melhor é que poderei fazer _merge_ aos poucos, conforme cada conflito resolvido.

Vou manter este _issue_ aberta até terminarmos de testar o processo.

**Comment by GuiDevloper** [comment]
Estou testando esse processo no meu repo, resolvendo conflitos, com umas leves dúvidas sobre arquivos novos como [src/coc/index](https://github.com/vuejs-br/br.vuejs.org/tree/dev/src/coc).
Eu não encontrei referência a ele (como no readme), onde ele é usado? Traduziremos ele depois?

**Comment by ErickPetru** [comment]
No momento não é um arquivo utilizado na interface, talvez passe a ser no futuro. Por enquanto não vejo motivos para traduzir.

**Comment by GuiDevloper** [comment]
Hey @ErickPetru, tudo bem contigo e o livro?
Justificando a ausência de atividade, estive sem óculos e também me aventurando a aprender React (eu sei, até eu sinto essa rivalidade, mas se você ler a Doc Br dele, vai querer até ajudá-los também) penso em expandir meu leque de ferramentas bem conhecidas. Existindo adventos como Vue ainda tento entender por quê React é tão requisitado.
Falando em requisitos, esses tempos eu ando buscando trabalho que me possibilite ajudar como faço aqui, seria uma honra receber dicas ou ideias, caso souber de algo já sou grato.

**Comment by ErickPetru** [comment]
Finalmente o _commit_ https://github.com/vuejs-br/br.vuejs.org/commit/6553b30f09c2dacc9d6d6edcf45d54f03cafb5e2 mesclou o trabalho realizado em _dev_ para o _master_, sem nenhum conflito. Me parece que o processo funcionou muito bem! Grande trabalho, parabéns!

**Comment by GuiDevloper** [comment]
É uma honra, os desafios dessas contribuições me ensinaram muito sobre Git e claro, sobre Vue.
Coisas novas que eu puder ajudar, só me deixar saber.
Para o futuro será interessante marcar um dia (e.g. a cada mês) para atualizar o `dev` e caso tenha conflitos criar uma _issue_.
