### ISSUE TITLE
Tradução do "coc\index.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#257]
O arquivo citado ainda não foi traduzido.

**Comment by rafaellaurindo** [comment]
Essa página foi traduzida nesse PR #258.

**Comment by ErickPetru** [comment]
Muito bom! Já foi para o ar no _merge_ de `dev` para `master` ocorrido no _commit_ https://github.com/vuejs-br/br.vuejs.org/commit/8e2bae1ae23d6818b157d99d49cbf50e3fa9864e.
