### ISSUE TITLE
Resolver conflitos em dev após merge de upstream/master

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#263]
Algumas modificações ocorridas em trechos de arquivos em `guide` e `cookbook` no repositório principal (_upstream_) entraram em conflito com as traduções atuais após o _commit_ https://github.com/vuejs-br/br.vuejs.org/commit/f6dfe5aa4d8cb2899272d8e7f32a5dbab898be79. As versões conflitantes devem ser corrigidas no _branch_ `dev` antes de serem mescladas em `master`.

**Comment by GuiDevloper** [comment]
Tudo bem, @ErickPetru?
Quero deixar anotado que fiquei feliz com a nova responsabilidade!
Lembrar que no começo tinha vergonha e aprendia a contribuir, hoje sou apaixonado por traduções e pelo trabalho lindo que todos fizeram nessa documentação.

**Comment by ErickPetru** [comment]
Olá @GuiDevloper, também quero deixar registrado meu agradecimento pelo bom trabalho que tem feito nessas revisões, certamente você merecia o acesso direto como membro do time!
