### ISSUE TITLE
Traduzir partes adicionadas em inglês

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/br.vuejs.org#265]
- [x] Trecho adicionado em [api/index](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/api/index.md) por [este commit](https://github.com/vuejs-br/br.vuejs.org/commit/c5043b82d5ca0237b86b9be79a99f718282ab15f)
- [x] Trecho adicionado em [guide/render-function](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/render-function.md) por [este commit](https://github.com/vuejs-br/br.vuejs.org/commit/12dc478d3a823fd729ae356e10712d419799b975)
- [x] Comentário adicionado em [guide/syntax](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/syntax.md) por [este commit](https://github.com/vuejs-br/br.vuejs.org/commit/ba6abb27c92868dfe38fb7bbfdad53be6bf7e0d8)
- [x] [resources/partners](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/resources/partners.md)
- [x] [layout/partners-page.ejs](https://github.com/vuejs-br/br.vuejs.org/blob/master/themes/vue/layout/partners-page.ejs)

**Comment by ErickPetru** [comment]
O trecho em [guide/render-function](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/render-function.md) foi resolvido no _commit_ a5b19ae1f23851ed8f68d171e42fdceefe34c4cb.

**Comment by GuiDevloper** [comment]
Olá @ErickPetru, espero que tudo bem.
Quero frisar que criei essa _issue_ buscando incentivar algo como a tag `good-first-issue` faz.
**São simples e úteis contribuições!**

Outra coisa, lembro que fiquei meio mal depois dos fatídicos _commits_ passados.
Meu humor apoiador quase me fez comentar algo como:
> -Foi culpa do estagiário!
> _-Que estagiário?_
> -Eu.

Na verdade quero me desculpar e estar pronto para a próxima coisa certa que farei!

**Comment by ErickPetru** [comment]
Olá @GuiDevloper, tudo bem? Não vejo motivos para você se desculpar. A _issue_ aqui aberta faz todo sentido e seria sensacional se outras pessoas resolvessem auxiliar nestes pequenos trechos carecendo de tradução.

**Comment by Gabrielr2508** [comment]
Olá, pessoal.

Enviei a tradução dos itens em aberto na PR #271.
