### ISSUE TITLE
Sintaxe de rebase na página dos Components Single-File

### ISSUE THREAD

**Issue by renangabriel27** [vuejs-br/br.vuejs.org#266]
- Eu estava lendo a documentação, e percebi que ficou uma sintaxe de rebase nessa página https://br.vuejs.org/v2/guide/single-file-components.html

![Screenshot from 2019-08-23 13-44-54](https://user-images.githubusercontent.com/10130724/63608968-881a9100-c5ac-11e9-8f72-eabdf8d61295.png)

**Comment by ErickPetru** [comment]
Olá @renangabriel27, obrigado pelo aviso! Acabo de corrigir no _commit_ a5b19ae1f23851ed8f68d171e42fdceefe34c4cb.
