### ISSUE TITLE
Resolver conflitos de merge em "cookbook/form-validation.md"

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/br.vuejs.org#269]
Após atualização a partir de _upstream_ inserida em `dev` pelo _commit_ 844d4bed619750a039a63085cc0ce4bd142e303e, o arquivo em [cookbook/form-validation.md](../blob/dev/src/v2/cookbook/form-validation.md) sofreu alterações drásticas e precisa ser todo revisado/retraduzido.

**Comment by GuiDevloper** [comment]
O `form-validation.md` tem algo que o deixou fadado ao super-conflito.
Deve ser a terceira vez que vejo uma pequena alteração fazer isso. :thinking:

**Comment by ErickPetru** [comment]
Também reparei isso @GuiDevloper, mas não consegui perceber o que poderia ser. Que bom que você enfrentou essa revisão trabalhosa pela terceira vez.

**Comment by GuiDevloper** [comment]
Estou aqui pra isso, @ErickPetru.
Acabei de deixar tudo sincronizado com a original usando `merge`.
Se houver algo no processo que eu possa fazer mais otimizado, basta avisar.

**Comment by ErickPetru** [comment]
Só pra confirmar, você sincronizou tudo em `dev`, certo?

**Comment by GuiDevloper** [comment]
Na verdade nos dois, me empolguei e commitei o update atual (após resolver conflitos) pro `master` antes do `dev`.
No fim, os dois estão atualizados com o `upstream`.

**Comment by ErickPetru** [comment]
Ótimo, então já foi tudo atualizado e está no ar. O repositório `master` está com integração contínua com a Netlify.
