### ISSUE TITLE
Tradução da documentação do vue-router

### ISSUE THREAD

**Issue by Gabrielr2508** [vuejs-br/br.vuejs.org#273]
Olá, pessoas!

Perdoem-me se esse não for o local indicado pra isso, mas como não achei nenhuma referência relacionada no repositório original nem na organização vuejs-br, resolvi perguntar por aqui mesmo.

Há algum esforço sendo realizado em relação à tradução da documentação do vue-router?

Observei que já existe tradução para o vuex, mas não para o vue-router.

Obrigado.

**Comment by GuiDevloper** [comment]
Exatamente isso que desejo que tenha uma atenção da comunidade.

Existem trabalhos iniciados em [vuejs-br/vue-router](https://github.com/vuejs-br/vue-router/issues), mas ainda não funcionou tão bem como essa doc.
Precisamos reunir ideias com o @ErickPetru, encontrando uma forma de continuar.

**Comment by ErickPetru** [comment]
Bom, como o @GuiDevloper comentou, temos o repositório [vuejs-br/vue-router](https://github.com/vuejs-br/vue-router), mas infelizmente ele nunca recebeu nenhuma atenção, tadinho.

Então, inspirado pela empolgação de vocês, acabei de fazer um `pull upstream` e deixá-lo pronto para o trabalho, deixando a pasta `docs/pt` criada e aproveitando para traduzir o primeiro arquivo, `README.md`, [neste commit](https://github.com/vuejs-br/vue-router/commit/ce0b00e110dc723982294171b67927092c4328b2). Podem botar a mão na massa!

Seguem algumas considerações:
- Ao contrário deste repositório, lá os trabalhos sempre acontecem no _branch_ `dev`.
- Muito tempo atrás eu criei [issues](https://github.com/vuejs-br/vue-router/issues) para organizar o que precisava ser traduzido, mas acho que a estrutura da documentação já mudou um bocado, então pode ser necessário fechar/abrir novas para organizar as coisas.
- Conforme [esta resposta](https://github.com/vuejs/vue-router/issues/2670) do Eduardo, nosso _fork_ é o local para os trabalhos nesta tradução. Somente quando estivermos com o conteúdo traduzido é que farei o _pull request_ e avisarei ele para publicar oficialmente lá.

Acho que é isso. Caso tenham alguma consideração adicional, me avisem.
Senão, vou fechar esta _issue_ e prosseguiremos as coisas naquele repositório.

**Comment by Gabrielr2508** [comment]
Por mim, tudo bem! Iniciarei assim que possível. Obrigado! 😄
