### ISSUE TITLE
Erro Ortografia

### ISSUE THREAD

**Issue by roberto0arruda** [vuejs-br/br.vuejs.org#277]
No tópico [Componentes Single-File](https://br.vuejs.org/v2/guide/single-file-components.html#Introducao) logo abaixo da Introdução o link para Lição gratuíta de Componentes Single-File com Vue.js:
a palavra gratuita não tem acento agudo e faltou um A, esta escrito como:
> ssista a uma vídeo-lição gratuita na Vue School

**Comment by ErickPetru** [comment]
Resolvido no último _commit_.
