### ISSUE TITLE
Página fora do ar

### ISSUE THREAD

**Issue by juliano-nunes** [vuejs-br/br.vuejs.org#278]
Alguém sabe o que ocorreu que a documentação está retornando apenas uma página em branco com status code 304?
![Screen Shot 2019-12-27 at 15 02 08](https://user-images.githubusercontent.com/22858307/71527374-e1c3fc80-28b9-11ea-89ed-7222be7156b4.png)

**Comment by ErickPetru** [comment]
Obrigado por avisar. O último deploy automático gerou algum problema, então fiz o rollback.

**Comment by juliano-nunes** [comment]
Estava avaliando aqui e parece que o problema foi causado pelo último merge. O arquivo [_config.yml](https://github.com/vuejs-br/br.vuejs.org/blob/master/themes/vue/_config.yml) está com anotações de conflito de merge.

<img width="319" alt="Screen Shot 2019-12-27 at 15 19 17" src="https://user-images.githubusercontent.com/22858307/71527940-4a13dd80-28bc-11ea-9607-36fd68f10411.png">


Esse é o primeiro erro que aparece no log do Netlify (`9:54:03 AM: ERROR Theme config load failed`).
