### ISSUE TITLE
Traduzir partes adicionadas em inglês

### ISSUE THREAD

**Issue by GuiDevloper** [vuejs-br/br.vuejs.org#283]
- [x] Trecho "Writing" adicionado em [README.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/README.md)
- [ ] Trecho adicionado em [theme-data.js](https://github.com/vuejs-br/br.vuejs.org/blob/master/themes/vue/source/js/theme-data.js)
- [x] Linha 688 em [api/index.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/api/index.md)
- [ ] Dados de Modus Create, Monterail e Rangle em [partners.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/resources/partners.md)
- [x] Linha 1890 em [style-guide/index.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/style-guide/index.md)
- [x] Linha 13 - 15 em [guide/installation.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/installation.md)
- [x] Linha 606 em [guide/components.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/components.md)
- [x] Linha 79 em [guide/index.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/index.md)
- [x] [security.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/security.md)
- [ ] [writing-guide.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/writing-guide.md)
- [ ] Código dos exemplos importados do CodeSandbox para as pastas vue-* em [examples](https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/examples)
(Abriu a possibilidade de traduzir, mas tem prioridade secundária)

**Comment by GuiDevloper** [comment]
-Exemplo de boa prática
Estou trabalhando no trecho "Writing" do README.

**Comment by juliano-nunes** [comment]
Estou trabalhando na tradução do 'writing-guide'

**Comment by abreumatheus** [comment]
Trabalhando na tradução de:
- Linha 13 - 15 em guide/installation.md

**Comment by abreumatheus** [comment]
Trabalhando na tradução de:
- Linha 606 em guide/components.md

**Comment by abreumatheus** [comment]
Trabalhando na tradução de:

- Linha 688 em api/index.md

**Comment by abreumatheus** [comment]
Trabalhando na tradução de:
- Linha 1890 em style-guide/index.md

**Comment by juliano-nunes** [comment]
Estou trabalhando na tradução do Writing Guide

**Comment by GuiDevloper** [comment]
Hey @ErickPetru, veja inbox do IN.

**Comment by abreumatheus** [comment]
> Estou trabalhando na tradução do Writing Guide

Se precisar de ajuda, estamos aí :)

**Comment by juliano-nunes** [comment]
@abreumatheus claro, toda ajuda é bem-vinda. Eu já trabalhei na introdução e primeira sessão (Princípios) e estou começando a segunda sessão (Organização). Se quiser pegar uma sessão pra traduzir, o artigo é bem longo e acho que vou demorar bastante se precisar traduzir ele todo sozinho.

**Comment by abreumatheus** [comment]
@juliano-nunes Vou pegar a Iteration & Communication e a Resources então, porque to com um pouquinho menos de tempo, mas se der pego mais uma :)

**Comment by gfda** [comment]
Olá, tenho interesse de contribuir de alguma forma.
Poderia começar a trabalhar na tradução do [theme-data.js](https://github.com/vuejs-br/br.vuejs.org/blob/master/themes/vue/source/js/theme-data.js) ?

**Comment by HmmerHead** [comment]
Olá. Tenho interesse em contribuir com a tradução. Alguém ainda esta trabalhando no [writing-guide.md](https://github.com/vuejs-br/br.vuejs.org/blob/master/writing-guide.md). Li algumas menções, porém, não sei se já concluíram. Caso ninguém esteja trabalhando nele, irei traduzi-la nos próximos dias.

**Comment by juliano-nunes** [comment]
Oi @HmmerHead, eu traduzi as primeiras sessões e o @abreumatheus tinha ficado de fazer as últimas, não sei se ele ainda pretende trabalhar nisso. Mas se quiser começar pela _Style_ ou _Grammar_, acho que ninguém pegou elas ainda.

**Comment by HmmerHead** [comment]
@juliano-nunes Vou pegar esses então. Obrigado pelo retorno

**Comment by vmeelo** [comment]
Estou trabalhando no writing-guide.md

**Comment by vmeelo** [comment]
Creio que no writing-guide.md precisa de uma revisão para possíveis erros ortográficos e traduzir a imagem. Não sei altera-la.

**Comment by ErickPetru** [comment]
Pessoal, depois de muita espera, **a permissão para tradução da nova documentação do Vue 3 foi liberada!**
O _core team_ já está ciente e os trabalhos serão conduzidos no _fork_: https://github.com/vuejs-br/docs-next.

Quem quiser ajudar, deve pegar uma das _issues_ já existentes (ou criar uma nova, caso queira começar traduzindo outra área da documentação que ainda não tem uma _issue_ criada). **Não se esqueça de avisar a todos sobre o que estará trabalhando, para evitarmos trabalhos duplicados em vão**.

_PS.: todas as ações na documentação da V2 serão interrompidas, portanto esta tarefa está sendo encerrada agora._

_PS2.: @GuiDevloper, se conseguir me ajudar a criar as _issues_ de todos os `.md`, vou ficar muito feliz. Criei várias e ainda não estou nem perto da metade!_

**Comment by GuiDevloper** [comment]
Opa @ErickPetru, bom estar de volta e com essa notícia animadora e desafiadora hehe
Já imaginei um bot criando issues com links para cada md, saquei a lógica.
Vou buscar ajudar sim e poderei organizar os Projects do novo Repo também?


PS: Vi umas partes da doc v2 mantidas, interessante levar em conta.

PS2: Eles já comentaram algo sobre o novo deploy? :)

**Comment by ErickPetru** [comment]
@GuiDevloper levei estas indagações para uma _issue_ no novo repositório, para deixar as coisas em ordem lá: https://github.com/vuejs-br/docs-next/issues/20. E já enviei seu _invite_ para mantenedor lá também.
