### ISSUE TITLE
Tradução do Vue.js 3

### ISSUE THREAD

**Issue by rafael-neri** [vuejs-br/br.vuejs.org#296]
Existe alguma iniciativa para traduzir a documentação da próxima versão do Vue.js?

Tenho interesse em contribuir com tradução, caso não exista nenhuma iniciativa eu gostaria de solicitar um fork de:
https://github.com/vuejs/docs-next

Se não for possível criar um novo repositório, pode ser usado uma branch separada nesse mesmo repositório.

**Comment by ErickPetru** [comment]
Olá @rafael-neri, que bom que deseja colaborar, mas a tradução da próxima versão ainda não deve iniciar, conforme recomendação do _core team_ [aqui](https://github.com/vuejs/vuejs.org/issues/2571). Vamos clonar o repositório somente quando a recomendação mudar.
