### ISSUE TITLE
Vue 3 Docs are ready for translation!

### ISSUE THREAD

**Issue by bencodezen** [vuejs-br/br.vuejs.org#302]
Hello! Just wanted to let you know that v3 docs are ready to start translating.

https://github.com/vuejs/docs-next

If you have any questions, please feel free to file an issue so we can help however we can!

**Comment by ErickPetru** [comment]
Hello @bencodezen, nice to hear it!
But how should we handle it right now?

I found that you're [thinking about Crowdin](https://github.com/vuejs/docs-next/issues/351), but not right now.
The new guide [still states that translations should not start](https://v3.vuejs.org/guide/contributing/translations.html#can-we-start-translating-vue-3-docs), so no instructions there too.

Should we just fork [docs-next](https://github.com/vuejs/docs-next) and start from scratch?
Is there already any _issue_ open for controlling the translations progresses?

**Comment by bencodezen** [comment]
@ErickPetru Good question. We're updating the docs to say that translations are ready. 

Since it's a new repo, we would recommend migrating over what makes sense, but there are a lot of structural changes that have been made.

As far as translation progresses, they can be tracked here for now: https://github.com/vuejs/docs-next/issues/478

Let me know if you have any other questions!

**Comment by ErickPetru** [comment]
Thanks @bencodezen, we'll work on the fork for now.
