### ISSUE TITLE
Referência de nome escrito com minúsculo

### ISSUE THREAD

**Issue by quaresmateo** [vuejs-br/br.vuejs.org#303]
Em https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/ssr.md e https://github.com/vuejs-br/br.vuejs.org/blob/master/src/v2/guide/deployment.md o nome de Webpack é iniciada com letra minúscula, enquanto que no restante da documentação está sendo iniciado com letra maiúscula.

**Comment by GuiDevloper** [comment]
Olá, @quaresmateo!
Agradecemos a contribuição, mas você nos pegou bem no momento de migração total para a [Doc da v3](https://github.com/vuejs-br/docs-next).

Mesmo assim, vou resolver isso, diz aí, está participando do _hacktoberfest_?

**Comment by quaresmateo** [comment]
Sim, estou participando do hacktoberfest

**Comment by GuiDevloper** [comment]
É que ia fazer contar essa contribuição, mas engraçado que não tenho poder de adicionar o tópico _hacktoberfest_ nesse repo (nova regra para repo participar)

Então @ErickPetru, o que me diria?

**Comment by GuiDevloper** [comment]
Ah, @quaresmateo, acabei de achar um jeito alternativo, já faço o merge.

**Comment by GuiDevloper** [comment]
@quaresmateo, se quiser continuar contribuindo é bem vindo na [nova Doc](https://github.com/vuejs-br/docs-next) que comentei, tem muita coisa boa à ser feita nessa evolução do Vue :)

**Comment by quaresmateo** [comment]
Opa, valeu!
