### ISSUE TITLE
Erros de português no Guia de Estilos

### ISSUE THREAD

**Issue by teffybiskup** [vuejs-br/br.vuejs.org#307]
Há alguns erros no Guia de Estilos traduzido, como falta de acento em 'às vezes', alguns typos ('mater' ao invés de 'manter', 'minúculas' ao invés de 'minúsculas', 'hífem' ao invés de 'hífen') e hífens desnecessários de acordo com o Acordo Ortográfico
(Estou participando do Hacktoberfest)
#306

**Comment by ErickPetru** [comment]
Olá @teffybiskup, agradecemos a contribuição e já mesclamos.

Contudo, se não for pedir demais, por favor foque os esforços no repositório https://github.com/vuejs-br/docs-next. Este repositório da V2 da documentação está congelado, já que o repositório da V3 será o repositório oficial assim que a tradução do Guia principal for concluída.
