### ISSUE TITLE
Onde fica a versão online?

### ISSUE THREAD

**Issue by neves** [vuejs-br/br.vuejs.org#54]
br.vuejs.org não existe, e também não está no menu do vue.js oficial. Qual o status deste projeto?

**Comment by ErickPetru** [comment]
@neves, infelizmente o projeto está parado. A documentação oficial recebeu muitas modificações com o lançamento da versão 2.2, assim o trabalho de tradução realizado anteriormente se tornou desalinhado, necessitando de pessoas dispostas a revisar comparativamente as duas versões.

Enquanto isso, pode acessar meu fork com o ponto onde paramos: https://erickpetru.github.io/br.vuejs.org/

Caso saiba de pessoas interessadas em colaborar neste processo, sinta-se à vontade para convidar aqui.

**Comment by theus** [comment]
@ErickPetru mas tem alguma pretensão de ser disponibilizado via meios oficiais tipo _br.vuejs.org_? Isso dá um ânimo na galera.

**Comment by ErickPetru** [comment]
@theus, certamente. E não é uma pretensão, é uma expectativa realista mesmo. Já temos tudo esquematizado para colocar o domínio BR no ar e o projeto brasileiro já foi oficializado com o time do Vue. Só não podemos colocar no ar no domínio correto enquanto estivermos defasados em relação ao documentação mais recente. Carecemos mesmo de mais participantes.

**Comment by theus** [comment]
@ErickPetru que bom ler isso! Então realmente dá pra continuar. Eu cheguei a pegar uma parte pra tradução mas vi que o repo estava parado e não peguei mais.

**Comment by neves** [comment]
Legal, vou participar também.

**Comment by neves** [comment]
Como faz, utilizo o seu https://github.com/erickpetru/br.vuejs.org ?

**Comment by ErickPetru** [comment]
@neves, as instruções do README deste repositório ainda estão valendo, ou seja:

- Crie um _fork_ para sua própria conta.
- Edite o arquivo README informando seu usuário onde estiver traduzindo/revisando.
- Faça um _pull request_ deste README para que todos possam ver aqui e não trabalhar na mesma coisa.
- Traduza/revise o arquivo que se propôs.
- Faça um _pull request_ do arquivo concluído para que possamos integrá-lo aqui.

Aproveito para ressaltar que acabei de fazer um grande _merge_ com as alterações mais recentes do guia oficial. Dessa forma, praticamente tudo que já estava traduzido possui agora alguns trechos em inglês, destacados com a marcação de conflitos `<<<<<<< HEAD =======`. Ou seja, além das poucas traduções que faltavam, precisamos todos nos unir para fazer uma grande revisão e atualização em tudo.

Agradecemos a colaboração e bom trabalho!

**Comment by neves** [comment]
@ErickPetru, será que foi uma boa comitar com as marcações de conflito? Porque agora eu não consigo utilizar ferramenta visual de diff. Não seria melhor deixar o upstream num branch separado e fazer o merge aos poucos a cada correção?

**Comment by ErickPetru** [comment]
@neves, sinceramente não pensei que seria um problema, pois aqui no Visual Studio Code fica bem evidente a parte dos conflitos para ir fazendo as correções. Mas sua sugestão faz sentido, podemos trabalhar assim no próximo _merge_. Aproveito para informar que atualizei o README explicando melhor nosso processo e deixando mais claras as padronizações que adotamos na tradução.

**Comment by mikejavier** [comment]
Galera em resumo... o projeto esta com os arquivos mais atualizados ? a lista de páginas que já esta com responsáveis, esta atualizada ?

**Comment by neves** [comment]
Sim @mikejavier, só seguir os passos acima.

**Comment by ErickPetru** [comment]
Agora que o domínio [br.vuejs.org](http://br.vuejs.org/) foi aceito como parte do projeto oficial, este tópico pode ser considerado concluído. Problemas específicos sobre partes da documentação ainda não revisadas devem ser tratados caso a caso com _Issues_ específicas.
