### ISSUE TITLE
Divergência em "Traduções padronizadas"

### ISSUE THREAD

**Issue by theus** [vuejs-br/br.vuejs.org#59]
![image](https://cloud.githubusercontent.com/assets/61322/24482688/a8ea111c-14c9-11e7-8b5c-694829cc291a.png)

**Comment by ErickPetru** [comment]
Resolvido no commit https://github.com/vuejs-br/br.vuejs.org/commit/ff8b7e9b83061cfeee4e72d34fbe428a0469d286.
