### ISSUE TITLE
Problemas de conflito

### ISSUE THREAD

**Issue by wilcorrea** [vuejs-br/br.vuejs.org#66]
Oi pessoal, identifiquei um conflito mal resolvido no link https://br.vuejs.org/v2/guide/custom-directive.html

Qual a orientação quanto a esses casos: PR ou abrir issue e vocês resolvem?

**Comment by danielschmitz** [comment]
Olá,

[corrigi](https://github.com/vuejs-br/br.vuejs.org/commit/28104de58e3358679bada15da9ae847f2d8f922b) esses erros hoje, só falta atualizar para o site novamente

**Comment by ErickPetru** [comment]
@wilcorrea, os conflitos de _merge_ foram um problema chato que durou algum tempo pois a documentação sofreu grandes atualizações para a versão 2.2. Como o @danielschmitz comentou, os conflitos terminaram de ser resolvidos hoje. Este tipo de problema realmente é melhor ser apontado como _issue_, da maneira que você fez, para que possamos corrigir diretamente.

Fora isso, acho legal enfatizar que a tradução está longe de ser considerada finalizada. De fato, acredito que ela nunca poderá ser "finalizada", pois cada nova versão do Vue traz algumas mudanças no guia e eventualmente mudanças na API. Neste momento, se der uma conferida aqui no README, vai ver que tem algumas coisas no guia que ainda precisam de tradução/revisão. E se quiser contribuir com a tradução da API, falta bastante coisa que nunca chegou a ser traduzida. Toda colaboração é bem-vinda!
