### ISSUE TITLE
Adicionar termos para não serem traduzidos

### ISSUE THREAD

**Issue by thiagorossener** [vuejs-br/br.vuejs.org#70]
Acredito que existem alguns termos que não devemos traduzir como "string templates", "array" e "input".

No README não fala nada sobre esses termos, mas não estou traduzindo eles.

**Comment by ErickPetru** [comment]
Tipos de dados não estão sendo traduzidos mesmo e nem faria sentido, não acho que falte especificar. Sobre _input_, deve ficar claro que o componente _input_ no sentido de "caixa de texto" não precisa ser traduzido, mas a ação de introduzir dados (_to input_) deve ser traduzida.

De qualquer forma, pode ficar à vontade para fazer um _pull request_ com tais termos no README, para ficar mais claro.
