### ISSUE TITLE
Trecho sem tradução

### ISSUE THREAD

**Issue by robertoentringer** [vuejs-br/br.vuejs.org#80]
O último parágrafo da página : br.vuejs.org/src/v2/guide/forms.md
ficou sem tradução.

![screen shot 2017-07-13 at 00 57 52](https://user-images.githubusercontent.com/1759811/28143653-feb8f3ca-6766-11e7-9efe-7c709ea8b9c1.jpg)

**Comment by ErickPetru** [comment]
Resolvido na última atualização (https://github.com/vuejs-br/br.vuejs.org/commit/3e5355decaf29befe8a1a1e766113cac7f09225b#diff-2329c7a812aea349f6d19677ca5953aa).
