### ISSUE TITLE
Complementando informações na seção: Reactivy

### ISSUE THREAD

**Issue by alexandesigner** [vuejs-br/br.vuejs.org#85]
Gostaria antes de mais nada agradecer o trabalho que já vem sendo feito, isso é incrível..

https://br.vuejs.org/v2/guide/reactivity.html#Declarando-Propriedades-Reativas

Logo abaixo possui um pedaço sem tradução.. Fiz um [PR](https://github.com/vuejs-br/br.vuejs.org/pull/84) com a tradução, talvez seja necessária uma pequena revisão.

`it eliminates a class of edge cases in the dependency tracking system, and also makes Vue instances play nicer with type checking systems.`

**Comment by ErickPetru** [comment]
Obrigado pela ajuda @alexandesigner. Fique à vontade para pegar outros conteúdos que ainda possuem partes em inglês para completar se puder.
